server:
  port: 8888

spring:
  application:
    name: config-center
  profiles:
    active: native
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
        import-check:
          enabled: false
    config:
      server:
        native:
          search-locations: classpath:/config

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans,configprops,httptrace,threaddump,heapdump,scheduledtasks,loggers,mappings
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
