-- 创建数据库
CREATE DATABASE IF NOT EXISTS system_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS nacos_config DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS erp_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS crm_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS mes_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS wms_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS srm_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS oa_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS hr_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS eam_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS hxcoe003 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

-- 创建用户并授权
CREATE USER IF NOT EXISTS 'aps_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'wms_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'qms_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'scm_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'srm_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'srm_sync'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'erp_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'bom_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'crm_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'oa_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'hr_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'mes_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'les_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'scada_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'ems_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'agv_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'scrm_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'opportunity_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'eam_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'plm_app'@'%' IDENTIFIED BY 'root';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `scm_db`.* TO 'scm_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `srm_db`.* TO 'srm_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `srm_db`.* TO 'srm_sync'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `plm_db`.* TO 'plm_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `erp_db`.* TO 'erp_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `wms_db`.* TO 'wms_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `oa_db`.* TO 'oa_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `crm_db`.* TO 'crm_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `mes_db`.* TO 'mes_app'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`aps\_%` TO 'aps_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`wms\_%` TO 'wms_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`qms\_%` TO 'qms_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`scm\_%` TO 'scm_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`srm\_%` TO 'srm_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`srm\_%` TO 'srm_sync'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`erp\_%` TO 'erp_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`bom\_%` TO 'bom_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`crm\_%` TO 'crm_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`oa\_%` TO 'oa_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`hr\_%` TO 'hr_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`mes\_%` TO 'mes_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`les\_%` TO 'les_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`scada\_%` TO 'scada_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`ems\_%` TO 'ems_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`agv\_%` TO 'agv_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`eam\_%` TO 'eam_app'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`scrm\_%` TO 'scrm_app'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON `hxcoe003`.`opportunity\_%` TO 'opportunity_app'@'%';

FLUSH PRIVILEGES;

-- 切换到system_db数据库
USE system_db;

-- 创建示例表
CREATE TABLE IF NOT EXISTS t_system_config (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    config_key VARCHAR(100) NOT NULL UNIQUE,
    config_value VARCHAR(255) NOT NULL,
    config_desc VARCHAR(255),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- 插入示例数据
INSERT INTO t_system_config (config_key, config_value, config_desc) VALUES
('system.name', 'Enterprise Management System', '系统名称'),
('system.version', '1.0.0', '系统版本'),
('system.description', '企业管理系统', '系统描述'),
('system.env', 'test', '系统环境');

-- 切换到nacos_config数据库
USE nacos_config;

-- Nacos会自动创建所需的表
