CREATE DATABASE IF NOT EXISTS `aps_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `hr_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `qms_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE mysql;

CREATE USER IF NOT EXISTS 'aps_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'hr_app'@'%' IDENTIFIED BY 'root';
CREATE USER IF NOT EXISTS 'qms_app'@'%' IDENTIFIED BY 'root';

GRANT ALL PRIVILEGES ON `aps_db`.* TO 'aps_app'@'%';
GRANT ALL PRIVILEGES ON `hr_db`.* TO 'hr_app'@'%';
GRANT ALL PRIVILEGES ON `qms_db`.* TO 'qms_app'@'%';

FLUSH PRIVILEGES;

